routes/web.php
<?php

use App\Http\Controllers\AdministratorController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\LoginController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\EventController;
use App\Http\Controllers\ArtikelController;
use App\Http\Controllers\BannerController;
use App\Http\Controllers\WaGroupController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [LoginController::class, 'index']);
Route::post('/login', [LoginController::class, 'login']);
Route::post('/logout', [LoginController::class, 'logout']);
Route::group(['middleware' => 'token'], function () {
    Route::get('/dashboard', [LoginController::class, 'dashboard'])->name('dashboard');
    
    Route::resource('administrator', AdministratorController::class);
    Route::put('admin/{id}/update-status', [AdministratorController::class, 'update_status'])->name('admin.update-status');
    Route::resource('user', UserController::class);
    Route::get('dataDashboard', [UserController::class, 'dataDashboard'])->name('user.dataDashboard');
    Route::put('user/acceptUser/{id}', [UserController::class, 'acceptUser'])->name('user.acceptUser');
    Route::delete('user/decline/{id}', [UserController::class, 'destroy'])->name('user.destroy');
    Route::get('user/{id}/detail', [UserController::class, 'detail'])->name('user.detail');
    Route::resource('event', EventController::class);
    Route::resource('artikel', ArtikelController::class);
    Route::resource('banner', BannerController::class);
    Route::post('banner/{id}/update-status', [BannerController::class, 'update_status'])->name('banner.update-status');
    Route::resource('wa-group', WaGroupController::class);
});

app/Http/Controllers/AdministratorController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use GuzzleHttp\Exception\GuzzleException;
use App\Services\BriEcoplayApi;
use GuzzleHttp\Client;
use Illuminate\Support\Facades\Log;
use Illuminate\Contracts\Filesystem\FileNotFoundException;
use stdClass;

class AdministratorController extends Controller
{
    protected $BriEcoplayApi;
    protected $errorAPI;

    public function __construct(BriEcoplayApi $BriEcoplayApi)
    {
        $this->BriEcoplayApi = $BriEcoplayApi;
        $this->errorAPI = 'API error : ';
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        if ($request->ajax()) {
            $page = ($request->start / $request->length) + 1;
            $limit = (string)$request->length;
            $response = $this->BriEcoplayApi->get('/admins?page='.$page.'&limit='.$limit.'&status=0');
            $dataAdmin = $response->result->data;
            $response = new stdClass();
            $response->data = datatables($dataAdmin->admin)->toJson();
            $response->draw = $response->data->original['draw'];
            $response->data->original['data'] = $dataAdmin->admin;
            $response->data->original['recordsFiltered'] = $dataAdmin->pagination->total_results;
            $response->data->original['recordsTotal'] = $dataAdmin->pagination->total_results;
            $response->recordsFiltered = $dataAdmin->pagination->total_results;
            $response->recordsTotal = $dataAdmin->pagination->total_results;
            return $response;
        }
        return view('administrator.index');
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update_status(Request $request, $id)
    {
        $payload = [
            'status' => (int) $request->status
        ];
        Log::debug(json_encode($payload));
        $response = $this->BriEcoplayApi->put('/admins/status/'.$id, $payload);
        $status = $response->status;

        echo $status;
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('administrator.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $payload = [
            'username' => $request->username,
            'full_name' => $request->full_name,
            'email' => $request->email,
            'password' => $request->password
        ];
        Log::debug(json_encode($payload));
        $response = $this->BriEcoplayApi->post('/register_admin', $payload);
        Log::debug(json_encode($response));

        return redirect()->route('administrator.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        return abort(404);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        return view('administrator.edit');
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/administrator/create.blade.php
@extends('layout.layout')

@section('title', 'Administrator')

@section('content')
    <div class="container mt-5">
        <div class="row">
            <div class="col-lg-6">
                <h5 class="font-weight-500">Tambah Admin</h5>
            </div>
        </div>
        <hr class="my-3">
        <form action="{{ route('administrator.store') }}" method="POST" >
            <input type="hidden" name="_token" id="csrf-token" value="{{ Session::token() }}" />
            <div class="row">
                <div class="col-lg-12">
                    <div class="form-group row">
                    
                        <div class="col-lg-4">
                            
                            <label for="" class="form-control-label">Nama</label>
                            <input type="text" name="full_name" class="form-control form-control-lg">
                        </div>
                    </div>
                    <div class="form-group mt-4 row">
                        <div class="col-lg-4">
                            <label for="" class="form-control-label">Username</label>
                            <input type="text" name="username" class="form-control form-control-lg">
                        </div>
                    </div>
                    <div class="form-group mt-4 row">
                        <div class="col-lg-4">
                            <label for="" class="form-control-label">Email</label>
                            <input type="text" name="email" class="form-control form-control-lg">
                        </div>
                    </div>
                    <!-- <div class="form-group mt-4 row">
                        <div class="col-lg-4">
                            <label for="" class="form-control-label">No HP</label>
                            <input type="text" class="form-control form-control-lg">
                        </div>
                    </div> -->
                    <div class="form-group mt-4 row">
                        <div class="col-lg-4">
                            <label for="" class="form-control-label">Password</label>
                            <input type="password" name="password" class="form-control form-control-lg">
                        </div>
                    </div>
                </div>
            </div>
            <hr class="my-5">
            <div class="row">
                <div class="col-lg-12">
                    <button type="submit" class="btn btn-primary btn-lg" id="submit">SIMPAN</button>
                </div>
            </div>
        </form>
    </div>
@endsection
@section('script')
    
@endsection

resources/views/administrator/edit.blade.php
@extends('layout.layout')

@section('title', 'Administrator')

@section('content')
    <div class="container mt-5">
        <div class="row">
            <div class="col-lg-6">
                <h5 class="font-weight-500">Detail Admin</h5>
            </div>
        </div>
        <hr class="my-3">
        <div class="row">
            <p style="font-weight: bold">Data Personal</p>
            <div class="col-lg-12">
                <table class="table table-borderless">
                    <tr>
                        <td>Nama</td>
                        <td>testes</td>
                    </tr>
                    <tr>
                        <td>Username</td>
                        <td>testes</td>
                    </tr>
                    <tr>
                        <td>Email</td>
                        <td>testes</td>
                    </tr>
                    <tr>
                        <td>Nomor HP</td>
                        <td>testes</td>
                    </tr>
                    <tr>
                        <td>Password</td>
                        <td>
                            <div class="form-group row">
                                <div class="col-4">
                                    <input type="password" class="form-control">    
                                </div>
                            </div>
                        </td>
                    </tr>
                </table>
            </div>
        </div>
        <hr class="my-5">
        <div class="row">
            <div class="col-lg-12">
                <a href="{{ route('administrator.update', 1) }}" class="btn btn-primary btn-lg">Ubah</a>
            </div>
        </div>
    </div>
@endsection

resources/views/administrator/index.blade.php
@extends('layout.layout')

@section('title', 'Administrator')

@section('content')
    <div class="container mt-5">
        <div class="row align-items-center">
            <div class="col-lg-6">
                <h5 class="font-weight-500">Administrator</h5>
            </div>
            <div class="col-lg-6">
                <a href="{{  route('administrator.create') }}" class="btn text-primary border-1 border-primary bg-transparent">+ Tambah Admin</a>
            </div>
        </div>
        <hr class="my-3">
        <div class="row">
            <div class="col-lg-12">
                <table class="table table-striped table-borderless" id="dataTable">
                    <thead>
                        <tr>
                            <th class="text-center py-3">No</th>
                            <th class="py-3">Nama Admin</th>
                            <th class="py-3">Username</th>
                            <th class="py-3">Email</th>
                            <th class="py-3">Status</th>
                        </tr>
                    </thead>
                </table>
            </div>
        </div>
    </div>
@endsection

@section('script')
    <script>
        function updateStatus(id, status) {
        console.log(id);
        let url = "{{ route('admin.update-status', 'id') }}";
        url = url.replace('id', id);
        $.ajax({
            type: 'PUT',
            url: url,
            data: {
                _token: "{{ csrf_token() }}",
                status: status
            },
            success: function(Resp) {
                alert('Status berhasil diubah!')
            },
            error: function(xhr, ajaxOptions, thrownError) {
                alert(xhr.status);
                alert(thrownError);
            }
        });
        return false;
    }

        $(document).ready(function(){
            $('#dataTable').DataTable({
                "pageLength": 10,
                processing: true,
                serverSide: true,
                ajax: {
                    url: "{{ route('administrator.index') }}",
                    dataSrc: 'data.original.data'
                },
                columns: [{
                        data: 'id',
                        name: 'id'
                    },
                    {
                        data: "full_name",
                        name: "full_name",
                        "render": function(data, type, full) {
                            if (!data)
                                return '-';
                            return data;
                        }
                    },
                    {
                        data: 'username',
                        name: 'username',
                        "render": function(data, type, full) {
                            if (!data)
                                return '-';
                            return data;
                        }
                    },
                    {
                        data: 'email',
                        name: 'email',
                        "render": function(data, type, full) {
                            if (!data)
                                return '-';
                            return data;
                        }
                    },
                    {
                        data: 'status',
                        name: 'status',
                        "render": function(data, type, full) {
                            let status = `<div class="form-check form-switch" onclick="updateStatus(${full.id}, ${data?'0':'1'})">
                                            <input class="form-check-input" type="checkbox" id="flexSwitchCheckDefault" ${data?'checked':''}>
                                        </div>`;
                            return status;
                        }
                    }
                ]
            });
        });
    </script>
@endsection